POST https://gerenciador-video.onrender.com/videos
Content-type: application/json

{
    "title": "(Armadilha do Diabo)",
    "description": "Supernatural - S01E22",
    "duration": 189
}


###
// se colocar um nome especifico depois do search= aparecera só o que foi pesquisado, se eu dar um send request sem nada e trocar o primeiro post vai adicionando mais dados para nosso BD

GET  https://gerenciador-video.onrender.com/videos


###

PUT  https://gerenciador-video.onrender.com/videos/5926e7bc-b946-4996-af9a-91cfad0f0463
Content-type: application/json

{
    "title": "Armadilha do Diabo",
    "description": "Supernatural - S01E22",
    "duration": 55
}

###

DELETE https://gerenciador-video.onrender.com/videos/116f7856-d509-4143-b9b0-38cc1d744b8a