POST https://gerenciador-video.onrender.com/videos
Content-type: application/json

{
    "title": "(Armadilha do Diabo)",
    "description": "Supernatural - S01E22",
    "duration": 189
}


###
// se colocar um nome especifico depois do search= aparecera só o que foi pesquisado, se eu dar um send request sem nada e trocar o primeiro post vai adicionando mais dados para nosso BD

GET  https://gerenciador-video.onrender.com/videos


###

PUT  https://gerenciador-video.onrender.com/videos/bf43e5cb-85e7-4598-beee-4d369338760f
Content-type: application/json

{
    "title": "Armadilha do Diabo",
    "description": "Supernatural - S01E22",
    "duration": 43
}

###

DELETE https://gerenciador-video.onrender.com/videos/fd0fd9d1-54f5-4a4e-8c2c-2ab20858566c